### ISSUE TITLE
Host with libraries down

### ISSUE THREAD

**Issue by eelke** [satoruhiga/ofxPCL#7]
The first step of the Setup instruction cannot be executed (`$ curl -O http://structor.jp/dist/ofxpcl_16_libs.zip`) , as the host (http://structor.jp) is down. Can you provide / host a copy of the libraries somewhere else? Thanks!

**Comment by satoruhiga** [comment]
opps...

reuploaded http://cl.ly/1D1Q3G072q3D/download/ofxpcl_16_libs.zip
